//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos_Maestros
    {
        public int alumno_id { get; set; }
        public string alumno_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public int id_maestro { get; set; }
        public string nombre_maestro { get; set; }
        public string primer_apellido_maestro { get; set; }
        public string segundo_apellido_maestro { get; set; }
    }
}
