//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestros_Grupos_Materias
    {
        public int id { get; set; }
        public Nullable<int> id_Maestros_Grupos { get; set; }
        public Nullable<int> id_materia { get; set; }
    
        public virtual Maestros_Grupos Maestros_Grupos { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
