//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrimariaDeLaRochaEntities : DbContext
    {
        public PrimariaDeLaRochaEntities()
            : base("name=PrimariaDeLaRochaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnos { get; set; }
        public virtual DbSet<Grado> Grados { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Maestro> Maestros { get; set; }
        public virtual DbSet<Maestros_Grupos> Maestros_Grupos { get; set; }
        public virtual DbSet<Maestros_Grupos_Materias> Maestros_Grupos_Materias { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Turno> Turnos { get; set; }
        public virtual DbSet<Alumnos_Materias> Alumnos_Materias { get; set; }
        public virtual DbSet<Alumnos_Maestros> Alumnos_Maestros { get; set; }
        public virtual DbSet<Calificaciones_Grupos_Actuales_Alumnos> Calificaciones_Grupos_Actuales_Alumnos { get; set; }
    }
}
